const PRODUCTS_FIRESTORE = 'products';
const CATEGORIES_FIRESTORE = 'categories';
const ORDERS_FIRESTORE = 'orders';
const STORES_FIRESTORE = 'stores';

export { PRODUCTS_FIRESTORE, CATEGORIES_FIRESTORE, ORDERS_FIRESTORE, STORES_FIRESTORE };
